Token: Mzk3MzYzMjk2MTcwMTQ3ODQw.DcTuGA.5q63rkk8d4SNqtSVm1sZT0ER9_Q
DB:
  Hostname: 185.230.161.112
  Port: 28015
  Database: GottBot
  User: admin
  Password: 51c1c65a-8764-5db1-b9b4-36f3a99a3186